### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#183]
Thinking about features we want to do next, for @mkarpicz and @Yuffster's sanity:

- [ ] Surveys + survey management
- [ ] Analytics + institute analytics
- [ ] YouTube segments (with analytics)
- [ ] Stripe integration for course payment
- [ ] Internationalisation, both chrome and course edit
- [ ] Custom CSS / styles for institute pages + institute static page management
- [ ] Custom domains for institutes

I'll try to keep this vaguely updated.
